//
//  CleanSwiftRouter.swift
//  Homework8_VIPER
//
//  Created by Кирилл Афонин on 29/10/2019.
//  Copyright (c) 2019 Кирилл Афонин. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CleanSwiftRoutingLogic {
    func setupAlert() -> UIAlertController
}

protocol CleanSwiftDataPassing {
    var dataStore: CleanSwiftDataStore? { get }
}

class CleanSwiftRouter: NSObject, CleanSwiftRoutingLogic, CleanSwiftDataPassing {
    
    weak var viewController: CleanSwiftViewController?
    var dataStore: CleanSwiftDataStore?
    
    // настройка всплывающего уведомления
    func setupAlert() -> UIAlertController {
        let alertController = UIAlertController(title: "Ошибка!", message: "Картинка не загружена!", preferredStyle: .alert)
        let action = UIAlertAction(title: "Загрузить",
                                   style: .default,
                                   handler: { (action: UIAlertAction) in
                                    self.viewController?.getImage()
        })
        alertController.addAction(action)
        
        let cancel = UIAlertAction(title: "Отмена", style: .cancel)
        alertController.addAction(cancel)
        return alertController
    }
    
}
