//
//  CleanSwiftPresenter.swift
//  Homework8_VIPER
//
//  Created by Кирилл Афонин on 29/10/2019.
//  Copyright (c) 2019 Кирилл Афонин. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanSwiftPresentationLogic {
    func presentImage(response: CleanSwift.ImageData.Response)
    func clearImage(response: CleanSwift.ImageData.Response)
}

class CleanSwiftPresenter: CleanSwiftPresentationLogic {
    weak var viewController: CleanSwiftDisplayLogic?
    
    // MARK: работа с картинкой
    
    func presentImage(response: CleanSwift.ImageData.Response) {
        
        if let image = response.image  {
            let viewModel = CleanSwift.ImageData.ViewModel(image: image)
            viewController?.displayImage(viewModel: viewModel)
        } else {
            viewController?.showAlert()
        }
    }
    
    func clearImage(response: CleanSwift.ImageData.Response) {
        let viewModel = CleanSwift.ImageData.ViewModel(image: response.image)
        viewController?.displayImage(viewModel: viewModel)
    }
    
}
