//
//  CleanSwiftInteractor.swift
//  Homework8_VIPER
//
//  Created by Кирилл Афонин on 29/10/2019.
//  Copyright (c) 2019 Кирилл Афонин. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanSwiftBusinessLogic {
    func getImage(request: CleanSwift.ImageData.Request)
    func setImage(request: CleanSwift.ImageData.Request)
    func clearCache(request: CleanSwift.ImageData.Request)
}

protocol CleanSwiftDataStore {
    var image: UIImage? { get set }
}

class CleanSwiftInteractor: CleanSwiftBusinessLogic, CleanSwiftDataStore {
    
    var presenter: CleanSwiftPresentationLogic?
    var worker: CleanSwiftWorker?
    var image: UIImage?
    
    // MARK: работа с изображением
    
    func getImage(request: CleanSwift.ImageData.Request) {
        worker = CleanSwiftWorker()
        worker?.downloadImage(completion: {
            image, error in
            self.image = image
            print("Картинка загружена: \(String(describing: self.image))")
        })

    }
    
    func setImage(request: CleanSwift.ImageData.Request) {
        let response = CleanSwift.ImageData.Response(image: image)
        presenter?.presentImage(response: response)
    }
    
    func clearCache(request: CleanSwift.ImageData.Request) {
        image = nil
        let response = CleanSwift.ImageData.Response(image: image)
        presenter?.clearImage(response: response)
    }
}
